name: fat_call
description: Try to make call with FCM.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
    git: https://github.com/personalizedrefrigerator/flutter_launcher_icons

flutter_icons:
  android: launcher_icon
  ios: false
  web: true
  image_path: assets/icon/icon.png

flutter:
  uses-material-design: true
